import type { Trade, Position } from "./types"

export const mockTrades: Trade[] = [
  {
    id: "trade-1",
    pair: "EURUSD",
    direction: "buy",
    entry: 1.0876,
    stop: 1.085,
    takeProfit: 1.093,
    agentType: "Day Trader",
    confidence: 4,
    riskReward: "1:2",
    winProbability: 68,
    exposure: 5,
    metaAgentRecommendation: "trade",
    metaAgentReason: "Strong bullish momentum with support at 1.0850",
  },
  {
    id: "trade-2",
    pair: "GBPUSD",
    direction: "sell",
    entry: 1.265,
    stop: 1.268,
    takeProfit: 1.259,
    agentType: "Scalper",
    confidence: 3,
    riskReward: "1:2",
    winProbability: 62,
    exposure: 5,
    metaAgentRecommendation: "no-trade",
    metaAgentReason: "High correlation risk with existing EURUSD position",
  },
  {
    id: "trade-3",
    pair: "USDJPY",
    direction: "buy",
    entry: 151.2,
    stop: 150.8,
    takeProfit: 152.0,
    agentType: "Swing",
    confidence: 5,
    riskReward: "1:2",
    winProbability: 75,
    exposure: 10,
    metaAgentRecommendation: "trade",
    metaAgentReason: "Strong technical breakout with favorable fundamentals",
  },
  {
    id: "trade-4",
    pair: "AUDUSD",
    direction: "sell",
    entry: 0.658,
    stop: 0.661,
    takeProfit: 0.652,
    agentType: "Position",
    confidence: 4,
    riskReward: "1:2",
    winProbability: 70,
    exposure: 7.5,
    metaAgentRecommendation: "trade",
    metaAgentReason: "Bearish trend continuation after resistance rejection",
  },
  {
    id: "trade-5",
    pair: "USDCAD",
    direction: "buy",
    entry: 1.365,
    stop: 1.362,
    takeProfit: 1.371,
    agentType: "Day Trader",
    confidence: 3,
    riskReward: "1:2",
    winProbability: 65,
    exposure: 5,
    metaAgentRecommendation: "no-trade",
    metaAgentReason: "Conflicting signals from economic data",
  },
]

export const mockPositions: Position[] = [
  {
    id: "pos-1",
    pair: "EURUSD",
    direction: "buy",
    entryPrice: 1.085,
    stopLoss: 1.082,
    takeProfit: 1.091,
    size: 0.1,
    openTime: "2023-06-10T10:30:00Z",
    pnl: 2.5,
    status: "open",
  },
  {
    id: "pos-2",
    pair: "USDJPY",
    direction: "sell",
    entryPrice: 152.3,
    stopLoss: 152.6,
    takeProfit: 151.7,
    size: 0.1,
    openTime: "2023-06-09T14:15:00Z",
    pnl: -0.8,
    status: "open",
  },
  {
    id: "pos-3",
    pair: "GBPUSD",
    direction: "buy",
    entryPrice: 1.258,
    stopLoss: 1.255,
    takeProfit: 1.264,
    size: 0.1,
    openTime: "2023-06-08T09:45:00Z",
    closeTime: "2023-06-08T16:30:00Z",
    pnl: 3.2,
    status: "closed",
  },
  {
    id: "pos-4",
    pair: "AUDUSD",
    direction: "sell",
    entryPrice: 0.662,
    stopLoss: 0.665,
    takeProfit: 0.656,
    size: 0.1,
    openTime: "2023-06-07T11:20:00Z",
    closeTime: "2023-06-07T20:15:00Z",
    pnl: -1.5,
    status: "closed",
  },
]
